### ISSUE TITLE
Change public directory to project directory

### ISSUE THREAD

**Issue by mvaptisv** [mvaptisv/candy-trade-bootstrap#3]
Just an idea, i think it could simplify developing.

**Comment by davelowensohn** [comment]
Cumbersome as it may seem, this is actually a good habit to get into, as most modern web frameworks use a similar file structure (Ruby on Rails, Ember.Js, etc.) The idea is that you (the superuser) always want to be able to go a directory above your website root - for instance, if you want to save backup archives or database dumps on the server - so you can make other folders that people can't access by typing `www.mysite.com/backups/` or whatever.

Also, in the abovementioned frameworks & others, you generally work on a bunch of different files that get "mixed down" into a single three-file package (`website.html`, `website.js`, `website.css`), the way an entire 128 track recording session gets "mixed down" into a single stereo audio track for the CD. You as a builder need a lot more room to work than the website visitor, and the `/public/` folder is where the build process spits out the compressed "final mixes" for fast, easy downloading.
